Company = 'Janis'
AppName = 'OpenNumismat'
Version = '1.10.6'
Web = 'https://opennumismat.github.io/'
Author = 'Vitaly Ignatov'
EMail = 'opennumismat@gmail.com'
License = 'GPLv3'
Portable = False
UserAgent = f"{AppName}/{Version} (+{Web}; contact: {EMail})"
