name: "Release"

on:
  push:

jobs:
  title:
    name: Title
    runs-on: ubuntu-latest
    outputs:
      APPNAME: OpenNumismat
      VERSION: ${{ steps.bump.outputs.current-version }}
      PACKAGENAME: OpenNumismat-${{ steps.bump.outputs.current-version }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install click==8.2 bump-my-version==0.32.1
    - name: Get current version
      id: bump
      shell: bash
      run: |
        echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

  nuitka_innosetup:
    needs: [title]
    name: Nuitka InnoSetup
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install nuitka
    - name: Create private keys
      run: |
        touch OpenNumismat/private_keys.py
        echo "COLNECT_PROXY = '${{ secrets.COLNECT_PROXY }}'" >> OpenNumismat/private_keys.py
        echo "COLNECT_KEY = '${{ secrets.COLNECT_KEY }}'" >> OpenNumismat/private_keys.py
        echo "NUMISTA_API_KEY = '${{ secrets.NUMISTA_API_KEY }}'" >> OpenNumismat/private_keys.py
        echo "MAPBOX_ACCESS_TOKEN = '${{ secrets.MAPBOX_ACCESS_TOKEN }}'" >> OpenNumismat/private_keys.py
    - name: build
      run: >-
        python -m nuitka open-numismat.py
        --jobs=2
        --assume-yes-for-downloads
        --msvc=latest
        --lto=yes
        --show-modules
        --standalone
        --enable-plugin=pyside6
        --include-qt-plugins=sqldrivers,multimedia
        --module-parameter=numba-disable-jit=yes
        --windows-console-mode=disable
        --include-data-dir=OpenNumismat/templates=templates
        --include-data-dir=OpenNumismat/db=db
        --include-data-files=COPYING=COPYING
        --windows-icon-from-ico=icons/main.ico
        --windows-file-version=${{ needs.title.outputs.VERSION }}
        --output-filename=${{ needs.title.outputs.APPNAME }}.exe
    - name: Upload
      id: upload-nuitka-exe
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.title.outputs.APPNAME }}-nuitka-exe
        path: open-numismat.dist/${{ needs.title.outputs.APPNAME }}.exe
        if-no-files-found: error
    - name: Signing
      uses: signpath/github-action-submit-signing-request@v1
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '3b087850-3844-4d25-8407-cf81e731f8d1'
        project-slug: 'open-numismat'
        signing-policy-slug: 'release-signing'
        artifact-configuration-slug: 'test-zip'
        github-artifact-id: '${{steps.upload-nuitka-exe.outputs.artifact-id}}'
        output-artifact-directory: open-numismat.dist
        wait-for-completion: true
        wait-for-completion-timeout-in-seconds: 3600
    - name: package
      run: |
        ISCC.exe tools/setup-nuitka.iss
    - name: Upload InnoSetup package
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.title.outputs.PACKAGENAME }}-nuitka
        path: tools/${{ needs.title.outputs.PACKAGENAME }}.exe
        if-no-files-found: error
    - name: Signing InnoSetup package
      uses: signpath/github-action-submit-signing-request@v1
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '3b087850-3844-4d25-8407-cf81e731f8d1'
        project-slug: 'open-numismat'
        signing-policy-slug: 'release-signing'
        artifact-configuration-slug: 'test-zip'
        github-artifact-id: '${{steps.upload.outputs.artifact-id}}'
        output-artifact-directory: .
        wait-for-completion: true
        wait-for-completion-timeout-in-seconds: 3600
    - name: upload-signed
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.title.outputs.PACKAGENAME }}-nuitka-signed
        path: ${{ needs.title.outputs.PACKAGENAME }}.exe
        if-no-files-found: error
